---
apiVersion: v1
kind: Secret
metadata:
  name: leosch1-leosch1-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/leosch1-gateway-gitops
